### ISSUE TITLE
Problem when updating list dynamically with new Index for fastscroll

### ISSUE THREAD

**Issue by Systems-Engineer** [volsahin/volx-recyclerview-fast-scroll#1]
The fastscroll only loads the current used indexes in my list items, but if i update the list with a new item wich have new Letter for indexes, the fastscroll doesnt refresh the letters... How can we do this?

Sorry for bad english

**Comment by volsahin** [comment]
I'm currently working on it now , today i will be releasing v1.0.5 which includes refresh feature too , thanks for your feedback

**Comment by volsahin** [comment]
v1.0.5 released , now you can update volx with by calling volx.notifyValueDataChanged() method. Be sure that you sorted your updated list again before calling this method.
