### ISSUE TITLE
Is that tvue samet?

### ISSUE THREAD

**Issue by oguzayan** [volsahin/volx-recyclerview-fast-scroll#2]
![screenshot_20170829-144205](https://user-images.githubusercontent.com/22585361/29819298-c07a89a2-8cc8-11e7-9cfe-ae8caba7f1ff.png)

**Comment by oguzayan** [comment]
hatayı çözersen yıldız vericem :)

**Comment by RecepK** [comment]
Çözmeden de verebilirsin =) 
Tebrikler arkadaşım.

**Comment by volsahin** [comment]
The reason of this issue was the user edit on android default text size. Problem fixed on v1.0.6.
@oguzayan Teşekkürler, çözdüm verebilirsin :)
@RecepK Teşekkürler.
