### ISSUE TITLE
View all sections

### ISSUE THREAD

**Issue by d3bt3ch** [volsahin/volx-recyclerview-fast-scroll#4]
How can i show all the sections while scrolling and highlight the section which is being scrolled over. For example much like google photos date scroller on the photos screen.

**Comment by volsahin** [comment]
I couldn't understand that clearly. It would be helpful if you provide an image about what you mention. Btw when you start touching recycler view Volx appears for the milliseconds you gave. You can highlight the letter with another color if you set another active color.
