### ISSUE TITLE
When calling notifyValueDataChanged() changes are appended to the existing indexes

### ISSUE THREAD

**Issue by captaintouch** [volsahin/volx-recyclerview-fast-scroll#8]
Hi!

I noticed that when calling notifyValueDataChanged() the new indexes were appended at the end instead of replacing them all.
I've made a pull request to clear the corresponding arrays before adding the contents to them again:
https://github.com/volsahin/volx-recyclerview-fast-scroll/pull/7

Thanks, really appreciate this component!

**Comment by volsahin** [comment]
I merged it. Thank you.
